# Generated by Django 3.2.4 on 2021-08-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210810_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='ts_end_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='ts_start_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holiday',
            name='sum_day',
            field=models.IntegerField(default=0),
        ),
    ]
