# Generated by Django 3.2.4 on 2021-08-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210811_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayoff',
            old_name='ts_end_date',
            new_name='ts_end_for_end_date',
        ),
        migrations.RenameField(
            model_name='dayoff',
            old_name='ts_start_date',
            new_name='ts_end_for_start_date',
        ),
        migrations.AddField(
            model_name='dayoff',
            name='ts_start_for_end_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='ts_start_for_start_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='sum_day',
            field=models.IntegerField(),
        ),
    ]
