# Generated by Django 3.2.4 on 2021-09-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210812_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='type_off',
        ),
        migrations.AddField(
            model_name='dayoff',
            name='type_off',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.DayOffType'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='last_update',
            field=models.IntegerField(default=0),
        ),
    ]
