# Generated by Django 3.2.4 on 2021-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210904_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='another_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
