# Generated by Django 3.2.4 on 2021-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Administrator')], max_length=10),
        ),
    ]
